title: Computer Sciencing Complex Systems
author: Anthony J. Clark and Jared M. Moore
description: A collection of posts from Drs. Clark and Moore and their students.

show_excerpts: false

theme: minima
